service: slack-integrations

frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-deployment-bucket
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.js
    excludeRegex: \.ts|\.test.ts|\.spec.ts|\.d.ts|\.map
    keepOutputDirectory: false
    serializedCompile: true
    packager: npm
  serverless-offline:
    allowCache: true
  dynamodb:
    stages:
      - default
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
      convertEmptyValues: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  stage: ${opt:stage, 'default'}
  region: ap-southeast-2
  timeout: 900
  architecture: arm64
  deploymentBucket:
    name: sls-deployment-${self:service}-${sls:stage}
    serverSideEncryption: AES256
    blockPublicAccess: true
    versioning: true
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  endpoint:
    handler: src/main.handler
    events:
      - httpApi:
          path: /slack/events
          method: post

resources:
  Resources:
    avacadoUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: avacadoUsersTable
        AttributeDefinitions:
          - AttributeName: slackID
            AttributeType: S
          - AttributeName: harvestAccountID
            AttributeType: S
          - AttributeName: harvestPAT
            AttributeType: S
        KeySchema:
          - AttributeName: slackID
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: pk-harvest
            KeySchema:
              - AttributeName: harvestAccountID
                KeyType: HASH
              - AttributeName: harvestPAT
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
