service: slack-integrations

frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-deployment-bucket
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    target: node16

provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  stage: ${opt:stage, 'default'}
  region: ap-southeast-2
  architecture: arm64
  deploymentBucket:
    name: sls-deployment-${self:service}-${sls:stage}
    serverSideEncryption: AES256
    blockPublicAccess: true
    versioning: true
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  endpoint:
    handler: lib/main.handler
    events:
      - httpApi:
          path: /slack/events
          method: post
